from django.conf.urls import patterns, url

from attendee import views

urlpatterns = patterns(
    '',
    url(regex=r'^$',
        view=views.AttendeeList.as_view(),
        name='list'),
    url(regex=r'^join/$',
        view=views.AttendeeJoin.as_view(),
        name='join'),
    url(regex=r'^shuffle/$',
        view=views.AttendeeShuffle.as_view(),
        name='shuffle'),
    url(regex=r'^check/(?P<code>[0-9A-Z]+)/$',
        view=views.AttendeeCheck.as_view(),
        name='check'),
    url(regex=r'^(?P<code>[0-9A-Z]+)/$',
        view=views.AttendeeDetail.as_view(),
        name='detail'),
    url(regex=r'^update/(?P<code>[0-9A-Z]+)/$',
        view=views.AttendeeUpdate.as_view(),
        name='update'),
    url(regex=r'^uncheck/(?P<code>[0-9A-Z]+)/$',
        view=views.AttendeeUncheck.as_view(),
        name='uncheck'),
    url(regex=r'^certificate/(?P<code>[0-9A-Z]+)/$',
        view=views.AttendeeCertificate.as_view(),
        name='certificate'),
    url(regex=r'^payment/(?P<code>[0-9A-Z]+)/$',
        view=views.AttendeePayment.as_view(),
        name='payment'),
    url(regex=r'^confirm/payment/(?P<code>[0-9A-Z]+)/$',
        view=views.AttendeeConfirmPayment.as_view(),
        name='confirm_payment'),
)
